// @generated by scripts/ci/generate-e2e-fixtures.py — DO NOT EDIT BY HAND.
//
// Source of truth: services/api/app/staging/synthetic_contract.py
// Regenerate:      python3 scripts/ci/generate-e2e-fixtures.py
// Drift is a CI failure (STG-01 guard + generator --check).
//
// NON-SECRET identity only. OTP codes and the run-scoped ticket scanner PIN are
// credentials: they arrive through the environment at run time and are never
// generated into source. The scanner TICKET ID is not a credential but is still
// absent: the real rsvp() service path mints it per run, so it is run state.

/** Reserved synthetic namespace. Every identifier below sits under it. */
export const SEED_PREFIX = "stg-rv-20260719";

/**
 * Content hash of the canonical fixture contract. A strict run asserts the
 * staging database was seeded from this exact generation. Derived only from
 * fixture identity — never from a timestamp, run id, or credential.
 */
export const FIXTURE_VERSION = "5b060652e939b51824131c5427199e7d";

/**
 * Canonical synthetic fixtures the specs depend on. These are public,
 * non-secret identifiers: no PII, no credentials.
 */
export const SEED = {
  /** Approved, KYC-passed vendor; also the organiser of the seeded event. */
  vendor: {
    slug: "stg-rv-20260719-vend-apr",
    handle: "stg-rv-20260719-vend-apr",
    displayName: "Synthetic approved vendor A",
  },
  /** Canonical product with buyable, in-stock listings from two vendors. */
  product: {
    slug: "stg-rv-20260719-product-a",
    name: "Synthetic multiseller product A",
  },
  /** Search term guaranteed to return the buyable product. */
  searchTerm: "multiseller",
  /**
   * The COD order the transactional fixture step places for the approved
   * vendor, through the real order-creation service. Single-listing product,
   * so the receiving vendor is deterministic rather than buy-box dependent.
   * The order id is NOT here: it is minted per run by the state machine.
   */
  codOrder: {
    productSlug: "stg-rv-20260719-product-b",
    productName: "Synthetic standard retail product B",
    qty: 1,
    unitPriceNgwee: 8750,
    subtotalNgwee: 8750,
    vendorSlug: "stg-rv-20260719-vend-apr",
    initialStatus: "placed",
  },
  /**
   * Published event with two ticket lanes. The SCANNER ticket id is NOT here:
   * it is claimed per run by the real `rsvp()` service path so it carries a
   * genuine `order_item_id`, which is what `POST /tickets/verify` requires
   * (`ticket_unpaid_hold` otherwise). Postgres mints that id, so it arrives
   * through `E2E_TICKET_ID` alongside the PIN, never from source.
   */
  event: {
    /**
     * Canonical event UUID. The organiser scanner route and the ticket verify
     * API are both keyed on this id, not on the public slug — `/organiser/events/{id}`
     * and `POST /tickets/verify` both look events up by primary key.
     */
    id: "e1000000-0000-4000-8000-000000000001",
    slug: "stg-rv-20260719-launch-expo",
    title: "Synthetic staging launch expo",
    /** The session both ticket lanes are allocated against. */
    instanceId: "e2000000-0000-4000-8000-000000000001",
    /** Paid lane — what the Lenco-gated purchase leg buys. */
    paidTicketTypeName: "General admission",
    /** Free-RSVP lane the per-run scanner ticket is issued on. */
    scannerTicketTypeName: "Scanner RSVP",
    /**
     * Statically seeded paid ticket. It has no `order_item_id` by construction,
     * so it can NEVER be checked in — it is the live negative control for
     * `ticket_unpaid_hold`, not a scanner subject. Do not fill it into the
     * scanner form expecting a pass.
     */
    unpaidHoldTicketId: "e4000000-0000-4000-8000-000000000001",
  },
  /** Landmark/GPS-style delivery address used at checkout (Lusaka). */
  address: {
    landmark: "Opposite stg-rv-20260719 vendor A pickup gate",
    area: "Lusaka",
    phone: "+260970000001",
  },
  /**
   * Role-specific login identities. A single account cannot serve both: the
   * personas carry distinct database roles (customer vs vendor), so the customer
   * journey and the vendor-portal journeys need separate phones. Only the OTP
   * CODES are secrets.
   */
  personas: {
    customer: {
      phone: "+260970000001",
      handle: "stg-rv-20260719-cust-01",
      role: "customer",
    },
    vendor: {
      phone: "+260970000004",
      handle: "stg-rv-20260719-vend-apr",
      role: "vendor",
      vendorSlug: "stg-rv-20260719-vend-apr",
    },
  },
} as const;
