// @generated by scripts/ci/generate-e2e-fixtures.py — DO NOT EDIT BY HAND.
//
// Source of truth: services/api/app/staging/synthetic_contract.py
// Regenerate:      python3 scripts/ci/generate-e2e-fixtures.py
// Drift is a CI failure (STG-01 guard + generator --check).
//
// NON-SECRET identity only. OTP codes and the run-scoped ticket scanner PIN are
// credentials: they arrive through the environment at run time and are never
// generated into source.

/** Reserved synthetic namespace. Every identifier below sits under it. */
export const SEED_PREFIX = "stg-rv-20260719";

/**
 * Content hash of the canonical fixture contract. A strict run asserts the
 * staging database was seeded from this exact generation. Derived only from
 * fixture identity — never from a timestamp, run id, or credential.
 */
export const FIXTURE_VERSION = "73d9223c0c8d6033093b96d31e037755";

/**
 * Canonical synthetic fixtures the specs depend on. These are public,
 * non-secret identifiers: no PII, no credentials.
 */
export const SEED = {
  /** Approved, KYC-passed vendor; also the organiser of the seeded event. */
  vendor: {
    slug: "stg-rv-20260719-vend-apr",
    handle: "stg-rv-20260719-vend-apr",
    displayName: "Synthetic approved vendor A",
  },
  /** Canonical product with buyable, in-stock listings from two vendors. */
  product: {
    slug: "stg-rv-20260719-product-a",
    name: "Synthetic multiseller product A",
  },
  /** Search term guaranteed to return the buyable product. */
  searchTerm: "multiseller",
  /** Published event with an un-scanned ticket for the organiser scanner. */
  event: {
    slug: "stg-rv-20260719-launch-expo",
    title: "Synthetic staging launch expo",
    ticketTypeName: "General admission",
    ticketId: "e4000000-0000-4000-8000-000000000001",
  },
  /** Landmark/GPS-style delivery address used at checkout (Lusaka). */
  address: {
    landmark: "Opposite stg-rv-20260719 vendor A pickup gate",
    area: "Lusaka",
    phone: "+260970000001",
  },
  /**
   * Role-specific login identities. A single account cannot serve both: the
   * personas carry distinct database roles (customer vs vendor), so the customer
   * journey and the vendor-portal journeys need separate phones. Only the OTP
   * CODES are secrets.
   */
  personas: {
    customer: {
      phone: "+260970000001",
      handle: "stg-rv-20260719-cust-01",
      role: "customer",
    },
    vendor: {
      phone: "+260970000004",
      handle: "stg-rv-20260719-vend-apr",
      role: "vendor",
      vendorSlug: "stg-rv-20260719-vend-apr",
    },
  },
} as const;
