import { seed as seedEnv, seedResetReady } from "./env";

/**
 * Canonical, deterministic fixtures the specs depend on. These slugs/ids are
 * stable across runs so the seed reset is idempotent: the reset endpoint
 * upserts (delete-by-key then recreate) exactly these rows — no autogenerated
 * ids, no cross-run bleed.
 *
 * NOTE: these are public, non-secret identifiers only. No PII, no credentials.
 */
export const SEED = {
  /** An approved, KYC-passed vendor able to list + fulfil. */
  vendor: {
    slug: "e2e-approved-vendor",
    displayName: "E2E Test Vendor",
  },
  /** A canonical product with a buyable, in-stock vendor listing. */
  product: {
    slug: "smartphone-x1",
  },
  /** A search term guaranteed to return the buyable product. */
  searchTerm: "smartphone",
  /** An event with unsold tickets available for purchase + scan. */
  event: {
    slug: "e2e-launch-expo",
  },
  /** Landmark/GPS-style delivery address used at checkout (Lusaka). */
  address: {
    landmark: "Opposite Manda Hill Mall, East Wing gate",
    area: "Lusaka",
    phone: "+260970000001",
  },
} as const;

/** Correlation id echoed in the reset request so staging logs can trace a run. */
export function runTag(): string {
  return `e2e-${process.env.GITHUB_RUN_ID ?? "local"}-${Date.now()}`;
}

/**
 * Idempotently reset the seed data before a run.
 *
 * Contract: a staging-only, token-guarded endpoint that rebuilds exactly the
 * SEED rows above. Calling it N times yields identical state (delete-by-slug +
 * recreate). When the reset env is absent (this build env — founder gate F9b)
 * the reset is a documented no-op so the non-payment flows can still run
 * against whatever data the target already holds.
 *
 * @returns true if a real reset ran; false if skipped (annotate the test).
 */
export async function resetSeed(): Promise<boolean> {
  if (!seedResetReady()) {
    return false;
  }
  const res = await fetch(seedEnv.resetUrl, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      // Bearer token from env/secret — never committed.
      authorization: `Bearer ${seedEnv.token}`,
    },
    body: JSON.stringify({
      runTag: runTag(),
      fixtures: {
        vendorSlug: SEED.vendor.slug,
        productSlug: SEED.product.slug,
        eventSlug: SEED.event.slug,
      },
    }),
  });
  if (!res.ok) {
    throw new Error(
      `Seed reset failed: ${res.status} ${res.statusText} — ${await res.text()}`,
    );
  }
  return true;
}
