#!/usr/bin/env python3
"""Generate the E2E fixture constants from the canonical staging contract.

`services/api/app/staging/synthetic_contract.py` is the single source of truth for
synthetic staging identity. The Playwright suite used to carry its own,
independently hand-authored set of slugs — which silently disagreed with what the
seeder actually creates, so seeded assertions could never pass. This emits the TS
view of the canonical contract instead, and `--check` fails CI when the committed
output drifts from the Python source.

Only NON-SECRET identity is emitted: slugs, handles, phone numbers and ids that
already live in the committed Python contract. OTP codes and the run-scoped
ticket PIN are credentials and are never written here.

Usage:
  python3 scripts/ci/generate-e2e-fixtures.py            # write the file
  python3 scripts/ci/generate-e2e-fixtures.py --check    # verify it is in sync
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "services" / "api"))

from app.staging.synthetic_contract import (  # noqa: E402
    CATALOG_FIXTURES,
    SEED_PREFIX,
    VENDOR_LOCATIONS,
    event_fixture,
    fixture_version,
    persona_by_key,
)

OUTPUT = REPO_ROOT / "e2e" / "fixtures" / "seed.generated.ts"

# Distinctive token from PRODUCT_A's title, so search must return the seeded
# multiseller product rather than incidental catalogue noise.
SEARCH_TERM = "multiseller"


def _ts(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    customer = persona_by_key("CUSTOMER_A")
    vendor = persona_by_key("APPROVED_VENDOR_A")
    product = CATALOG_FIXTURES[0]
    event = event_fixture("EVENT_LAUNCH_EXPO")
    ticket_type = event.ticket_types[0]
    ticket = event.tickets[0]
    location = next(loc for loc in VENDOR_LOCATIONS if loc.vendor_key == "APPROVED_VENDOR_A")

    return f"""// @generated by scripts/ci/generate-e2e-fixtures.py — DO NOT EDIT BY HAND.
//
// Source of truth: services/api/app/staging/synthetic_contract.py
// Regenerate:      python3 scripts/ci/generate-e2e-fixtures.py
// Drift is a CI failure (STG-01 guard + generator --check).
//
// NON-SECRET identity only. OTP codes and the run-scoped ticket scanner PIN are
// credentials: they arrive through the environment at run time and are never
// generated into source.

/** Reserved synthetic namespace. Every identifier below sits under it. */
export const SEED_PREFIX = {_ts(SEED_PREFIX)};

/**
 * Content hash of the canonical fixture contract. A strict run asserts the
 * staging database was seeded from this exact generation. Derived only from
 * fixture identity — never from a timestamp, run id, or credential.
 */
export const FIXTURE_VERSION = {_ts(fixture_version())};

/**
 * Canonical synthetic fixtures the specs depend on. These are public,
 * non-secret identifiers: no PII, no credentials.
 */
export const SEED = {{
  /** Approved, KYC-passed vendor; also the organiser of the seeded event. */
  vendor: {{
    slug: {_ts(vendor.slug or "")},
    handle: {_ts(vendor.handle)},
    displayName: {_ts("Synthetic approved vendor A")},
  }},
  /** Canonical product with buyable, in-stock listings from two vendors. */
  product: {{
    slug: {_ts(product.product_slug)},
    name: {_ts(product.product_name)},
  }},
  /** Search term guaranteed to return the buyable product. */
  searchTerm: {_ts(SEARCH_TERM)},
  /** Published event with an un-scanned ticket for the organiser scanner. */
  event: {{
    slug: {_ts(event.slug)},
    title: {_ts(event.title)},
    ticketTypeName: {_ts(ticket_type.name)},
    ticketId: {_ts(ticket.ticket_id)},
  }},
  /** Landmark/GPS-style delivery address used at checkout (Lusaka). */
  address: {{
    landmark: {_ts(location.landmark)},
    area: {_ts(location.area)},
    phone: {_ts(customer.phone)},
  }},
  /**
   * Role-specific login identities. A single account cannot serve both: the
   * personas carry distinct database roles (customer vs vendor), so the customer
   * journey and the vendor-portal journeys need separate phones. Only the OTP
   * CODES are secrets.
   */
  personas: {{
    customer: {{
      phone: {_ts(customer.phone)},
      handle: {_ts(customer.handle)},
      role: {_ts(customer.user_role)},
    }},
    vendor: {{
      phone: {_ts(vendor.phone)},
      handle: {_ts(vendor.handle)},
      role: {_ts(vendor.user_role)},
      vendorSlug: {_ts(vendor.slug or "")},
    }},
  }},
}} as const;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs from the canonical contract.",
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not OUTPUT.exists():
            print(
                f"::error::{OUTPUT.relative_to(REPO_ROOT)} is missing — run "
                "python3 scripts/ci/generate-e2e-fixtures.py",
                file=sys.stderr,
            )
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"::error::{OUTPUT.relative_to(REPO_ROOT)} is out of sync with "
                "services/api/app/staging/synthetic_contract.py — run "
                "python3 scripts/ci/generate-e2e-fixtures.py and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"generated E2E fixtures in sync (fixture_version={fixture_version()})")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} (fixture_version={fixture_version()})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
