#!/usr/bin/env python3
"""Generate the E2E fixture constants from the canonical staging contract.

`services/api/app/staging/synthetic_contract.py` is the single source of truth for
synthetic staging identity. The Playwright suite used to carry its own,
independently hand-authored set of slugs — which silently disagreed with what the
seeder actually creates, so seeded assertions could never pass. This emits the TS
view of the canonical contract instead, and `--check` fails CI when the committed
output drifts from the Python source.

Only NON-SECRET identity is emitted: slugs, handles, phone numbers and ids that
already live in the committed Python contract. OTP codes and the run-scoped
ticket PIN are credentials and are never written here, and the scanner ticket id
is omitted because `rsvp()` mints it per run (see `app.staging.event_scanner`).

Usage:
  python3 scripts/ci/generate-e2e-fixtures.py            # write the file
  python3 scripts/ci/generate-e2e-fixtures.py --check    # verify it is in sync
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT / "services" / "api"))

from app.staging.synthetic_contract import (  # noqa: E402
    CATALOG_FIXTURES,
    SEED_PREFIX,
    VENDOR_LOCATIONS,
    event_fixture,
    fixture_version,
    paid_ticket_type,
    persona_by_key,
    scanner_ticket_type,
)
from app.staging.transactional import cod_placed_fixture  # noqa: E402

OUTPUT = REPO_ROOT / "e2e" / "fixtures" / "seed.generated.ts"

# Distinctive token from PRODUCT_A's title, so search must return the seeded
# multiseller product rather than incidental catalogue noise.
SEARCH_TERM = "multiseller"


def _ts(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render() -> str:
    customer = persona_by_key("CUSTOMER_A")
    vendor = persona_by_key("APPROVED_VENDOR_A")
    product = CATALOG_FIXTURES[0]
    event = event_fixture("EVENT_LAUNCH_EXPO")
    paid_type = paid_ticket_type(event)
    scanner_type = scanner_ticket_type(event)
    unpaid_hold = event.tickets[0]
    location = next(loc for loc in VENDOR_LOCATIONS if loc.vendor_key == "APPROVED_VENDOR_A")
    cod = cod_placed_fixture()

    return f"""// @generated by scripts/ci/generate-e2e-fixtures.py — DO NOT EDIT BY HAND.
//
// Source of truth: services/api/app/staging/synthetic_contract.py
// Regenerate:      python3 scripts/ci/generate-e2e-fixtures.py
// Drift is a CI failure (STG-01 guard + generator --check).
//
// NON-SECRET identity only. OTP codes and the run-scoped ticket scanner PIN are
// credentials: they arrive through the environment at run time and are never
// generated into source. The scanner TICKET ID is not a credential but is still
// absent: the real rsvp() service path mints it per run, so it is run state.

/** Reserved synthetic namespace. Every identifier below sits under it. */
export const SEED_PREFIX = {_ts(SEED_PREFIX)};

/**
 * Content hash of the canonical fixture contract. A strict run asserts the
 * staging database was seeded from this exact generation. Derived only from
 * fixture identity — never from a timestamp, run id, or credential.
 */
export const FIXTURE_VERSION = {_ts(fixture_version())};

/**
 * Canonical synthetic fixtures the specs depend on. These are public,
 * non-secret identifiers: no PII, no credentials.
 */
export const SEED = {{
  /** Approved, KYC-passed vendor; also the organiser of the seeded event. */
  vendor: {{
    slug: {_ts(vendor.slug or "")},
    handle: {_ts(vendor.handle)},
    displayName: {_ts("Synthetic approved vendor A")},
  }},
  /** Canonical product with buyable, in-stock listings from two vendors. */
  product: {{
    slug: {_ts(product.product_slug)},
    name: {_ts(product.product_name)},
  }},
  /** Search term guaranteed to return the buyable product. */
  searchTerm: {_ts(SEARCH_TERM)},
  /**
   * The COD order the transactional fixture step places for the approved
   * vendor, through the real order-creation service. Single-listing product,
   * so the receiving vendor is deterministic rather than buy-box dependent.
   * The order id is NOT here: it is minted per run by the state machine.
   */
  codOrder: {{
    productSlug: {_ts(cod.product_slug)},
    productName: {_ts(cod.product_name)},
    qty: {cod.qty},
    unitPriceNgwee: {cod.unit_price_ngwee},
    subtotalNgwee: {cod.subtotal_ngwee},
    vendorSlug: {_ts(vendor.slug or "")},
    initialStatus: {_ts("placed")},
  }},
  /**
   * Published event with two ticket lanes. The SCANNER ticket id is NOT here:
   * it is claimed per run by the real `rsvp()` service path so it carries a
   * genuine `order_item_id`, which is what `POST /tickets/verify` requires
   * (`ticket_unpaid_hold` otherwise). Postgres mints that id, so it arrives
   * through `E2E_TICKET_ID` alongside the PIN, never from source.
   */
  event: {{
    /**
     * Canonical event UUID. The organiser scanner route and the ticket verify
     * API are both keyed on this id, not on the public slug — `/organiser/events/{{id}}`
     * and `POST /tickets/verify` both look events up by primary key.
     */
    id: {_ts(event.event_id)},
    slug: {_ts(event.slug)},
    title: {_ts(event.title)},
    /** The session both ticket lanes are allocated against. */
    instanceId: {_ts(event.instance_id)},
    /** Paid lane — what the Lenco-gated purchase leg buys. */
    paidTicketTypeName: {_ts(paid_type.name)},
    /** Free-RSVP lane the per-run scanner ticket is issued on. */
    scannerTicketTypeName: {_ts(scanner_type.name)},
    /**
     * Statically seeded paid ticket. It has no `order_item_id` by construction,
     * so it can NEVER be checked in — it is the live negative control for
     * `ticket_unpaid_hold`, not a scanner subject. Do not fill it into the
     * scanner form expecting a pass.
     */
    unpaidHoldTicketId: {_ts(unpaid_hold.ticket_id)},
  }},
  /** Landmark/GPS-style delivery address used at checkout (Lusaka). */
  address: {{
    landmark: {_ts(location.landmark)},
    area: {_ts(location.area)},
    phone: {_ts(customer.phone)},
  }},
  /**
   * Role-specific login identities. A single account cannot serve both: the
   * personas carry distinct database roles (customer vs vendor), so the customer
   * journey and the vendor-portal journeys need separate phones. Only the OTP
   * CODES are secrets.
   */
  personas: {{
    customer: {{
      phone: {_ts(customer.phone)},
      handle: {_ts(customer.handle)},
      role: {_ts(customer.user_role)},
    }},
    vendor: {{
      phone: {_ts(vendor.phone)},
      handle: {_ts(vendor.handle)},
      role: {_ts(vendor.user_role)},
      vendorSlug: {_ts(vendor.slug or "")},
    }},
  }},
}} as const;
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the committed file differs from the canonical contract.",
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        if not OUTPUT.exists():
            print(
                f"::error::{OUTPUT.relative_to(REPO_ROOT)} is missing — run "
                "python3 scripts/ci/generate-e2e-fixtures.py",
                file=sys.stderr,
            )
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != rendered:
            print(
                f"::error::{OUTPUT.relative_to(REPO_ROOT)} is out of sync with "
                "services/api/app/staging/synthetic_contract.py — run "
                "python3 scripts/ci/generate-e2e-fixtures.py and commit the result",
                file=sys.stderr,
            )
            return 1
        print(f"generated E2E fixtures in sync (fixture_version={fixture_version()})")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} (fixture_version={fixture_version()})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
