/**
 * Placeholder database types — regenerated by `pnpm gen:types` once Supabase lands (M03-P10).
 */
export type Database = Record<string, never>;

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
