#!/usr/bin/env python3
"""Generate bem/nya Phase-1 critical overlay JSON files from flat translation maps."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
MSG = ROOT / "packages" / "i18n" / "messages"

PREFIXES: dict[str, list[str]] = {
    "common": ["app", "common", "nav", "theme", "greeting", "offline", "install"],
    "catalog": [
        "home.meta",
        "home.nav",
        "home.hero",
        "home.trust",
        "home.demo",
        "home.categories",
        "home.rails",
        "home.sellCta",
        "browseCategories",
        "plp.title",
        "plp.defaultCategory",
        "plp.breadcrumbAria",
        "plp.results",
        "plp.emptyTitle",
        "plp.emptyBody",
        "plp.unavailableTitle",
        "plp.unavailableBody",
        "plp.card",
        "plp.loadMore",
        "plp.loading",
        "pdp",
        "returnableBadge",
    ],
    "search": [
        "title",
        "placeholder",
        "submit",
        "recent",
        "tabs",
        "noResults",
        "unavailable",
        "invalid",
        "suggestionTerms",
        "suggestions",
        "categories",
        "askVergeo",
        "results",
        "input",
        "pagination",
        "result",
    ],
    "checkout": [
        "cart",
        "checkout.pageTitle",
        "checkout.stepAnnouncement",
        "checkout.doneIndicator",
        "checkout.steps",
        "checkout.payment",
        "checkout.review",
        "checkout.pending",
        "checkout.ussd",
        "checkout.card",
        "checkout.emptyCart",
        "checkout.error",
        "checkout.loading",
        "checkout.stockUnavailable",
        "checkout.reservationExpired",
    ],
    "orders": [
        "title",
        "empty",
        "list",
        "detail.title",
        "detail.back",
        "detail.orderId",
        "detail.vendor",
        "detail.total",
        "status",
        "timeline",
        "escrow",
        "errors",
    ],
    "account": ["title", "nav", "locales", "common"],
    "marketing": ["notFound", "error"],
}


def flatten(obj: Any, prefix: str = "") -> dict[str, str]:
    out: dict[str, str] = {}
    if not isinstance(obj, dict):
        return out
    for k, v in obj.items():
        if k == "__fallback":
            continue
        p = f"{prefix}.{k}" if prefix else k
        if isinstance(v, str):
            out[p] = v
        elif isinstance(v, dict):
            out.update(flatten(v, p))
    return out


def unflatten(flat: dict[str, str]) -> dict[str, Any]:
    root: dict[str, Any] = {}
    for key, value in flat.items():
        parts = key.split(".")
        cur = root
        for part in parts[:-1]:
            nxt = cur.get(part)
            if not isinstance(nxt, dict):
                nxt = {}
                cur[part] = nxt
            cur = nxt
        cur[parts[-1]] = value
    return root


def matches(key: str, prefixes: list[str]) -> bool:
    return any(key == p or key.startswith(p + ".") for p in prefixes)


# ---------------------------------------------------------------------------
# Bemba (bem) — tone from notifications.json (yenu, Lemeni, yasuminishwa, …)
# ---------------------------------------------------------------------------
BEM: dict[str, dict[str, str]] = {
    "common": {
        "app.name": "Vergeo5",
        "common.loading": "Ilekete…",
        "common.retry": "Wesheni limbi",
        "nav.home": "Kwenu",
        "nav.skipToContent": "Pita ku content",
        "theme.label": "Cilangululo",
        "theme.light": "Cilanguka",
        "theme.dark": "Cishilikisha",
        "theme.system": "System ya device",
        "greeting": "Muli shani, {name}!",
        "offline.code": "Offline",
        "offline.heading": "Tamuli pa network",
        "offline.body": "Takwaba connection nomba. Amapeji mwalola kale yakonka — connecteni limbi ukutwala ifyonse.",
        "offline.retry": "Wesheni limbi",
        "offline.home": "Bweleleni kwenu",
        "install.title": "Instaleni Vergeo5",
        "install.body": "Longeni Vergeo5 pa home screen pakuti mwafikemo bwangu no app full-screen.",
        "install.action": "Instala app",
        "install.dismiss": "Nomba te",
        "install.updateBody": "Version yambi ya Vergeo5 yaisa.",
        "install.updateAction": "Reload uku update",
    },
    "catalog": {
        "home.meta.title": "Sanga Zambia",
        "home.meta.description": "Shita ifintu, booka services, no sanga events mu Zambia pa Vergeo5.",
        "home.nav.ariaLabel": "Navigation ya shop",
        "home.nav.bottomAriaLabel": "Navigation ikalamba ya shop",
        "home.nav.home": "Kwenu",
        "home.nav.browse": "Twaleni",
        "home.nav.ask": "Ipusheni",
        "home.nav.orders": "Ama-order",
        "home.nav.account": "Akaunti",
        "home.nav.cart": "Ing'anda ya ifintu",
        "home.nav.searchPlaceholder": "Fweni ifintu, services, events…",
        "home.nav.searchSubmit": "Fweni",
        "home.nav.allCategories": "Categories shyonse",
        "home.nav.categoriesPanelAria": "Categories shyonse",
        "home.nav.categoriesLoading": "Ilekete categories…",
        "home.nav.viewAllCategories": "Loleni categories shyonse",
        "home.nav.services": "Imilimo",
        "home.nav.events": "Ificitike",
        "home.nav.askVergeo": "Ipusheni Vergeo",
        "home.nav.supplies": "Ifya business",
        "home.nav.desktopAriaLabel": "Navigation ikalamba",
        "home.hero.eyebrow": "Marketplace ya Zambia",
        "home.hero.fallbackTitle": "Sanga ifintu, services, no events mu Zambia",
        "home.hero.fallbackSubtitle": "Compare prices ukufuma ku basellers mu Zambia, no arrange delivery ya Lusaka nangu pickup nationwide ilyo listing yaisa.",
        "home.hero.primaryCta": "Tampeniko kutwala",
        "home.hero.secondaryCta": "Sambeni ukushitisha",
        "home.hero.placeholder.title": "Mwaiseni pa Vergeo5",
        "home.hero.placeholder.subtitle": "Storefront yenu ya config ileisa apa ilyo merchandising slots fyaya live.",
        "home.hero.escrowLine": "Ukulindilila kwa buyer na escrow ilyo payment ya online yaisa — yikwata bwino na Vergeo5 mpaka kufika, elyo yasuminishwa.",
        "home.hero.escrowStep1": "Mwalipila",
        "home.hero.escrowStep2": "Yikwata bwino na Vergeo5",
        "home.hero.escrowStep3": "Yasuminishwa pa kufika",
        "home.trust.ariaLabel": "Cinshi muleshita pa Vergeo5",
        "home.trust.sellers": "Amaprofiles ya basellers no status mwingalola",
        "home.trust.fulfillment": "Delivery ya Lusaka nangu pickup nationwide ilyo listing yaisa",
        "home.trust.returns": "Amabuloshi ya returns no refunds ku ama-order ayasuminishwa",
        "home.trust.escrow": "Ilyo payment ya online yaisa, Vergeo5 yikwata bwino indalama yenu mpaka kufika",
        "home.demo.sampleListing": "Listing ya sample",
        "home.categories.title": "Shiteni na category",
        "home.categories.viewAll": "Categories shyonse",
        "home.categories.browseLabel": "Twaleni {category}",
        "home.rails.newTitle": "Ifyapya pa Vergeo5",
        "home.rails.departmentTitle": "Ifyapya mu {category}",
        "home.rails.viewAll": "Loleni fyonse",
        "home.rails.servicesTitle": "Imilimo",
        "home.rails.vendorsTitle": "Basellers abakalamba",
        "home.rails.services.provider": "Na {provider}",
        "home.rails.services.fromPrice": "Ukufuma",
        "home.rails.services.noReviews": "Provider umupya",
        "home.rails.services.view": "Loleni service",
        "home.rails.vendors.listings": "Ifintu",
        "home.rails.vendors.reviews": "Ama-reviews",
        "home.rails.vendors.rating": "{rating} ({count})",
        "home.rails.vendors.noReviews": "Uupya",
        "home.rails.vendors.preferred": "Asalwa",
        "home.rails.vendors.verified": "Yasuminishwa",
        "home.rails.vendors.location": "Zambia",
        "home.rails.vendors.view": "Piteni ku store",
        "home.sellCta.title": "Ukushitisha pa Vergeo5 kulifye kwa invite nomba",
        "home.sellCta.body": "Signup ya public teyaisa kale. Basellers abaitwa bengakonka onboarding; bambi bengasamba ifyo seller beta ikonka.",
        "home.sellCta.cta": "Sambeni ukushitisha",
        "browseCategories.title": "Twaleni categories",
        "browseCategories.subtitle": "Shiteni departments sha Phase-1 no subcategories shabo.",
        "browseCategories.emptyTitle": "Takwaba categories",
        "browseCategories.emptyBody": "Catalogue takwete categories sha public nomba. Bweleleni limbi, nangu fweni.",
        "browseCategories.unavailableTitle": "Categories tashifikapo",
        "browseCategories.unavailableBody": "Tatwaishibe ukuleta category tree nomba. Wesheni limbi, nangu fweni.",
        "plp.title": "Twaleni {category}",
        "plp.defaultCategory": "Ifintu fyonse",
        "plp.breadcrumbAria": "Inshila ya peji",
        "plp.results": "{count, plural, one {# listing} other {# amalistings}}",
        "plp.emptyTitle": "Takwaba listings",
        "plp.emptyBody": "Wesheni ukufuta filters nangu twaleni category yambi.",
        "plp.unavailableTitle": "Listings tashifikapo",
        "plp.unavailableBody": "Tatwaishibe ukuleta ifintu fyamu category iyi nomba. Wesheni limbi, nangu fweni.",
        "plp.card.vendor": "Ashitisha {vendor}",
        "plp.card.noReviews": "Takwaba ama-reviews",
        "plp.card.reviewCount": "({count})",
        "plp.card.quickAdd": "Longeni bwangu",
        "plp.card.wishlist": "Sungileni ku wishlist",
        "plp.card.outOfStock": "Takwaba mu stock",
        "plp.card.distance": "{distance} ukutali",
        "plp.loadMore": "Leteni fimbi",
        "plp.loading": "Ilekete…",
        "pdp.meta.notFoundTitle": "Icintu tacisangwa",
        "pdp.meta.descriptionFallback": "Shiteni {name} pa Vergeo5",
        "pdp.tabs.ariaLabel": "Ifya product",
        "pdp.tabs.overview": "Icifupi",
        "pdp.tabs.specs": "Ifya nshita",
        "pdp.tabs.reviews": "Ama-reviews",
        "pdp.overview.heading": "Ifilondolola",
        "pdp.related.heading": "Fimbi mu category iyi",
        "pdp.related.fromPrice": "Ukufuma {price}",
        "pdp.gallery.empty": "Takwaba amapictures",
        "pdp.gallery.indicator": "Picture {current} ya {total}",
        "pdp.gallery.previous": "Picture iyapita",
        "pdp.gallery.next": "Picture iyakonka",
        "pdp.specs.heading": "Ifya specs",
        "pdp.specs.empty": "Takwaba specifications",
        "pdp.buyBox.priceLabel": "Mutengo",
        "pdp.buyBox.quantityLabel": "Ubunji",
        "pdp.buyBox.decrease": "Kucesha ubunji",
        "pdp.buyBox.increase": "Kukusha ubunji",
        "pdp.buyBox.decreaseSymbol": "-",
        "pdp.buyBox.increaseSymbol": "+",
        "pdp.buyBox.addToCart": "Longeni mu cart",
        "pdp.buyBox.addingToCart": "Ilelenga…",
        "pdp.buyBox.addToCartError": "Tatwaishibe ukulenga mu cart. Checkeni connection no wesheni limbi.",
        "pdp.buyBox.inStock": "Ili mu stock",
        "pdp.buyBox.outOfStock": "Takwaba mu stock",
        "pdp.buyBox.lowStock": "Hashala {count} fye",
        "pdp.buyBox.alwaysAvailable": "Yaisa",
        "pdp.buyBox.singleVendor": "Ashitisha vendor uyu fye",
        "pdp.buyBox.moq": "Order iyacalamba: {count}",
        "pdp.vendor.heading": "Ushitisha",
        "pdp.vendor.preferredBadge": "Seller preferred",
        "pdp.vendor.noReviews": "Takwaba ama-reviews",
        "pdp.vendor.rating": "{rating} ({count, plural, one {# review} other {# ama-reviews}})",
        "pdp.vendor.viewStore": "Loleni store",
        "pdp.trust.preferredSeller": "Seller preferred — {name}",
        "pdp.trust.seller": "Ashitisha {name}",
        "pdp.trust.delivery": "Delivery yaisa ku seller uyu",
        "pdp.trust.pickup": "Pickup yaisa ku seller uyu",
        "pdp.trust.returns": "Returns no refunds",
        "pdp.trust.escrow": "Ilyo payment ya online yaisa, Vergeo5 yikwata bwino indalama yenu mpaka kufika. COD yengasuminishwa ku ama-order ayasuminishwa.",
        "pdp.condition.new": "Cipya",
        "pdp.condition.refurbished": "Cilukilwe",
        "returnableBadge.label": "Cingabwelela mu nsiku {days}",
    },
    "search": {
        "title": "Fweni",
        "placeholder": "Fweni pa Vergeo5",
        "submit": "Fweni",
        "recent.title": "Ifyo mwafwene kale",
        "recent.clear": "Futeni fyonse",
        "recent.remove": "Futeni {term}",
        "tabs.ariaLabel": "Filter results na type",
        "tabs.all": "Fyonse",
        "tabs.products": "Ifintu",
        "tabs.services": "Imilimo",
        "tabs.events": "Ificitike",
        "tabs.supplies": "Ifya business",
        "tabs.vendors": "Basellers",
        "tabs.count": "{label} ({count})",
        "noResults.title": "Takwaba results ku \"{query}\"",
        "noResults.suggestionsTitle": "Wesheni ukufwenya",
        "noResults.categoriesTitle": "Twaleni categories",
        "unavailable.title": "Search teyaisa",
        "unavailable.body": "Tatwaishibe ukuleta search results nomba. Wesheni limbi, nangu twaleni categories.",
        "unavailable.retry": "Wesheni limbi",
        "invalid.title": "Search iyi ndai",
        "invalid.body": "Cesheni query no wesheni limbi. Filters no sorting mu URL tashaluka.",
        "suggestionTerms.phones": "amafoni",
        "suggestionTerms.chitenge": "icitenge",
        "suggestionTerms.kitchenware": "ifya kitchen",
        "suggestionTerms.lusakaVendors": "basellers ba Lusaka",
        "suggestions.term": "Wesheni ukufwenya {term}",
        "categories.electronics": "Ifya elektrik",
        "categories.fashion": "Ifya kwisala",
        "categories.home": "Kwenu no living",
        "categories.groceries": "Groceries no staples",
        "askVergeo.title": "Ipusheni Vergeo",
        "askVergeo.teaser": "Tamwishibe ico mufwaya? Ipusheni Vergeo pakuti mwafwena ico mufwaya.",
        "askVergeo.slotLabel": "Slot ya Ask Vergeo assistant",
        "results.count": "{count, plural, one {# result} other {# amaresults}}",
        "results.degraded": "Twalanga keyword matches (semantic search teyaisa)",
        "input.ariaLabel": "Fweni",
        "input.suggestionsLabel": "Amasuggestions ya search",
        "input.noSuggestions": "Takwaba amasuggestions",
        "pagination.loadMore": "Leteni fimbi",
        "pagination.loading": "Ilekete fimbi…",
        "result.priceFrom": "Ukufuma {price}",
        "result.category": "Mu {category}",
    },
    "checkout": {
        "cart.title": "Cart yenu",
        "cart.emptyTitle": "Cart yenu iyapwa",
        "cart.emptyBody": "Twaleni ifintu no longeni items pakuti mwampe.",
        "cart.browseCta": "Konkeni ukushita",
        "cart.itemCount": "{count, plural, one {# item} other {# ama-items}}",
        "cart.subtotal": "Subtotal yafye",
        "cart.total": "Yonse",
        "cart.vendorGroup": "Ashitisha vendor",
        "cart.vendorSubtotal": "Subtotal ya vendor: {amount}",
        "cart.lineTotal": "Total ya line: {amount}",
        "cart.unitPrice": "{amount} cimo cimo",
        "cart.remove": "Futeni",
        "cart.removeLabel": "Futeni {title} ukufuma mu cart",
        "cart.qtyDecrease": "Kucesha ubunji",
        "cart.qtyIncrease": "Kukusha ubunji",
        "cart.qtyDecreaseSymbol": "-",
        "cart.qtyIncreaseSymbol": "+",
        "cart.qtyValue": "Ubunji: {count}",
        "cart.updating": "Ileluka…",
        "cart.updateError": "Tatwaishibe ukuluka ubunji. Twabwelela ku amount iyasungwa.",
        "cart.addToCart": "Longeni mu cart",
        "cart.adding": "Ilelenga…",
        "cart.added": "Yalongwa mu cart",
        "cart.addError": "Tatwaishibe ukulenga mu cart. Wesheni limbi.",
        "cart.viewCart": "Loleni cart",
        "cart.checkoutCta": "Piteni ku checkout",
        "cart.miniCartTitle": "Summary ya cart",
        "cart.miniCartClose": "Isaleni cart",
        "cart.openCart": "Isuleni cart",
        "cart.deliveryEligible": "Subtotal ya vendor yaisuminisha free Lusaka delivery — zone yalangwa pa checkout",
        "cart.deliveryHint": "Longeni {amount} limbi ukufuma ku vendor uyu pakuti mwasumina free Lusaka delivery",
        "cart.deliveryThreshold": "Free Lusaka delivery ukufuma {threshold} pa vendor",
        "cart.deliveryScopeNote": "Yakonka fye mu zones sha delivery sha Lusaka. Kunse kwa Lusaka, pickup yaisa. Zone fees shikonka ilyo muli panshi ya threshold.",
        "cart.freeDeliveryProgress": "{amount} ya {threshold} ku free Lusaka delivery",
        "cart.freeDeliveryUnlocked": "Subtotal ya vendor iyi yaisuminisha free Lusaka delivery",
        "cart.noticesTitle": "Fimbi fyalyaluka",
        "cart.noticePriceChanged": "Price yaluka ukufuma {oldPrice} ku {newPrice}",
        "cart.noticeOutOfStock": "Ici cintu tacili mu stock",
        "cart.noticeQtyReduced": "Hashala {available} fye — ubunji bwaluka ukufuma {requested}",
        "cart.outOfStockLine": "Takwaba mu stock",
        "checkout.pageTitle": "Ukushita",
        "checkout.stepAnnouncement": "Step {current} ya {total}",
        "checkout.doneIndicator": "✓",
        "checkout.steps.contact": "Contact yenu",
        "checkout.steps.fulfilment": "Ukufika",
        "checkout.steps.payment": "Ukulipila",
        "checkout.steps.review": "Ukulola",
        "checkout.payment.title": "Mufwaya ukulipila shani?",
        "checkout.payment.subtitle": "Payment yenu yikwata bwino mpaka kufika.",
        "checkout.payment.momo": "Indalama sha mobile",
        "checkout.payment.card": "Debit nangu credit card",
        "checkout.payment.cod": "Cash ilyo yafika",
        "checkout.payment.railMtn": "MTN MoMo",
        "checkout.payment.railAirtel": "Airtel Money (MoMo)",
        "checkout.payment.payerLabel": "Nambala ya payer",
        "checkout.payment.payerHelp": "Nambala iyakwata USSD payment prompt.",
        "checkout.payment.payerPlaceholder": "97X XXX XXX",
        "checkout.payment.countryCode": "Code ya calo",
        "checkout.payment.nationalNumber": "Nambala ya mobile",
        "checkout.payment.cardExplainer": "Pantu mwaisa place order, mukompleta card payment pa Lenco secure hosted page. Vergeo5 tayamona ifya card yenu.",
        "checkout.payment.codIneligible": "Cash on delivery yaisa fye ku ama-order mpaka {cap}.",
        "checkout.payment.continue": "Konkeni ku review",
        "checkout.payment.loading": "Lemeni…",
        "checkout.payment.required": "Lemeni nambala ya payer",
        "checkout.payment.invalidPayer": "Lemeni nambala ya Zambia iyasuminishwa",
        "checkout.payment.railRequired": "Saleni mobile money network",
        "checkout.payment.codRejected": "Cash on delivery teyaisa ku total iyi ya order",
        "checkout.payment.railRejected": "Mobile money network iyi teyasuminishwa",
        "checkout.payment.error": "Tatwaishibe ukusunga payment method. Wesheni limbi.",
        "checkout.payment.paymentsDisabled": "Payment ya online teyaisa nomba. Longeni Cash on Delivery ilyo yaisa, nangu wesheni limbi.",
        "checkout.review.title": "Loleni order yenu",
        "checkout.review.subtitle": "Checkeni fyonse fyabwino pantu mulipila.",
        "checkout.review.lineItems": "Ifintu",
        "checkout.review.qty": "×{qty}",
        "checkout.review.subtotal": "Subtotal yafye",
        "checkout.review.deliveryFees": "Amafees ya delivery",
        "checkout.review.total": "Yonse",
        "checkout.review.paymentMethod": "Ifyo mulipila",
        "checkout.review.methodMomo": "Indalama sha mobile ({rail})",
        "checkout.review.methodCard": "Card (secure hosted page)",
        "checkout.review.methodCod": "Cash ilyo yafika",
        "checkout.review.railMtn": "MTN",
        "checkout.review.railAirtel": "Airtel",
        "checkout.review.payerNumber": "Uwalipila: {number}",
        "checkout.review.escrowTitle": "Ifyo payment yenu ilindililwa",
        "checkout.review.escrowStep1": "Mwalipila",
        "checkout.review.escrowStep2": "Yikwata bwino na Vergeo5",
        "checkout.review.escrowStep3": "Yasuminishwa pa kufika",
        "checkout.review.consentLabel": "Nasuminisha Terms & Conditions no Privacy Policy",
        "checkout.review.consentRequired": "Suminisheni Terms & Conditions pakuti mukonke",
        "checkout.review.placeOrder": "Isa order",
        "checkout.review.loading": "Lemeni…",
        "checkout.pending.pageTitle": "Suminisheni payment",
        "checkout.pending.loading": "Ilelola payment status…",
        "checkout.pending.error": "Tatwaishibe ukuleta payment status. Wesheni limbi.",
        "checkout.pending.pollAria": "Tuletekele approval ya mobile money",
        "checkout.pending.successRedirect": "Tulemitwala ku order yenu…",
        "checkout.pending.confirmingTitle": "Tulesuminisha payment yenu",
        "checkout.pending.confirmingBody": "Twapoka signal ya payment no tulesuminisha order yenu. Ici teci final paid confirmation — loleni order status ku escrow updates.",
        "checkout.pending.codTitle": "Order yaisa — lipileni pa delivery",
        "checkout.pending.codBody": "Sungeni {amount} mu cash ilyo order yenu yafika. Courier wesu akapoka payment pa delivery.",
        "checkout.pending.codCta": "Loleni ifya order",
        "checkout.pending.cancelledTitle": "Payment yafutwa",
        "checkout.pending.cancelledBody": "Mwakana mobile money prompt. Mungawesha limbi nangu saleni payment method yambi pa checkout.",
        "checkout.pending.cancelledCta": "Bweleleni ku checkout",
        "checkout.pending.timeoutTitle": "Payment yafwile time",
        "checkout.pending.timeoutBody": "USSD prompt yafwile pantu yasuminishwa. Checkeni phone yenu ili na network, elyo wesheni — tutuma prompt yambi ku order imo.",
        "checkout.pending.retry": "Wesheni payment",
        "checkout.pending.retrying": "Tulemituma prompt yambi…",
        "checkout.pending.retryError": "Tatwaishibe ukuwesha payment. Checkeni connection no wesheni limbi.",
        "checkout.pending.viewOrder": "Loleni order",
        "checkout.ussd.title": "Loleni phone yenu",
        "checkout.ussd.subtitle": "Suminisheni prompt ya {amount} pa phone yenu pakuti mukomplete payment.",
        "checkout.ussd.amountLabel": "Amount iyasuminishwa",
        "checkout.ussd.mtnHelp": "Isuleni MTN MoMo prompt pa phone yenu no lemeni PIN pakuti musuminishe {amount}.",
        "checkout.ussd.airtelHelp": "Isuleni Airtel Money prompt pa phone yenu no lemeni PIN pakuti musuminishe {amount}.",
        "checkout.ussd.genericHelp": "Mobile money prompt yatuminwa ku phone yenu. Lemeni PIN pakuti musuminishe {amount}.",
        "checkout.ussd.waiting": "Tuletekele approval…",
        "checkout.ussd.doNotClose": "Sungileni peji ili open ilyo musuminisha pa phone.",
        "checkout.card.pageTitle": "Lipileni na card",
        "checkout.card.subtitle": "Kompleteni payment yenu secure pa Lenco. Vergeo5 tayamona ifya card yenu.",
        "checkout.card.loading": "Ilepanga secure payment…",
        "checkout.card.openingWidget": "Ileisa Lenco secure payment…",
        "checkout.card.verifying": "Ilelola payment yenu…",
        "checkout.card.successTitle": "Order yasuminishwa",
        "checkout.card.successBody": "Order yenu yasuminishwa no payment yikwata bwino na Vergeo5. Mungalola ifya order nomba.",
        "checkout.card.viewOrders": "Loleni ama-order yenu",
        "checkout.card.failedTitle": "Payment tacikomplete",
        "checkout.card.failedBody": "Card payment tayaipita. Mungawesha limbi ukufuma ku checkout.",
        "checkout.card.retryPayment": "Bweleleni ku payment",
        "checkout.card.heldTitle": "Payment ilelolwa",
        "checkout.card.heldBody": "Tatwaishibe ukusuminisha payment iyi automatic. Team yesu yalishibikwa — mulipile limbi pantu tusuminisha.",
        "checkout.card.pendingTitle": "Ilekonka",
        "checkout.card.pendingBody": "Tuletekele final confirmation ukufuma ku Lenco. Peji iyi ileluka limbi.",
        "checkout.card.error": "Icintu caciluka. Wesheni limbi.",
        "checkout.card.widgetUnavailable": "Card payments tashaisa nomba. Wesheni mobile money nangu limbi.",
        "checkout.card.widgetLabel": "Order ya Vergeo5",
        "checkout.card.secureNote": "Yasungwa na Lenco — PCI compliant hosted checkout",
        "checkout.emptyCart": "Cart yenu iyapwa.",
        "checkout.error": "Icintu caciluka. Wesheni limbi.",
        "checkout.loading": "Iletampa checkout…",
        "checkout.stockUnavailable": "Icimo tacili mu stock. Loleni cart yenu.",
        "checkout.reservationExpired": "Reservation yenu yafwile — ifintu fyabwelela mu cart yenu.",
    },
    "orders": {
        "title": "Ama-order yenu",
        "empty.title": "Takwaba ama-order",
        "empty.body": "Ilyo mwashita ukufuma ku basellers ba Vergeo5, ama-order no tracking fyaisa apa.",
        "empty.cta": "Tampeniko ukushita",
        "list.checkoutGroup": "Ukushita {date}",
        "list.vendorOrder": "Ukufuma ku {vendor}",
        "list.itemCount": "{count, plural, one {# item} other {# ama-items}}",
        "list.total": "Yonse {amount}",
        "list.viewOrder": "Loleni order",
        "list.status": "Status yali: {status}",
        "list.paymentCod": "Lipileni pa delivery",
        "list.paymentPrepaid": "Yalipilwa kale",
        "detail.title": "Ifya order",
        "detail.back": "Bweleleni ku ama-order",
        "detail.orderId": "Order nambala {id}",
        "detail.vendor": "Ashitisha {vendor}",
        "detail.total": "Total ya order",
        "status.placed": "Yaiswa",
        "status.confirmed": "Yasuminishwa",
        "status.processing": "Ilepangwa",
        "status.ready": "Yikwete kale ku pickup",
        "status.shipped": "Yatumizwa",
        "status.delivered": "Yafika",
        "status.completed": "Yapwa",
        "status.cancelled": "Yafutwa",
        "status.refunded": "Refund ilekonka",
        "timeline.title": "Progress ya order",
        "timeline.placed": "Order yaiswa",
        "timeline.paymentHeld": "Mwalipila — yikwata bwino na Vergeo5",
        "timeline.paymentCod": "Lipileni vendor pa delivery",
        "timeline.confirmed": "Vendor yasuminisha order yenu",
        "timeline.processing": "Vendor ilepanga order yenu",
        "timeline.ready": "Yikwete kale ku pickup",
        "timeline.shipped": "Ileisa kuli imwe",
        "timeline.delivered": "Yafika",
        "timeline.completed": "Payment yasuminishwa ku vendor",
        "timeline.cancelled": "Order yafutwa",
        "timeline.refunded": "Refund ku mobile money yenu",
        "escrow.held": "Payment yenu yikwata bwino na Vergeo5 mpaka mupoke order yenu.",
        "escrow.released": "Indalama shyasuminishwa ku vendor pantu fulfilment.",
        "escrow.refunded": "Refund ilebwelela ku mobile money wallet yenu.",
        "escrow.cod": "Lipileni vendor mu cash nangu mobile money ilyo mupoka order.",
        "errors.loadFailed": "Tatwaishibe ukuleta ama-order yenu. Wesheni limbi.",
        "errors.notFound": "Order tacasangwa",
    },
    "account": {
        "title": "Account yandi",
        "nav.profile": "Profile yenu",
        "nav.addresses": "Ama-addresses",
        "nav.preferences": "Amanotifications",
        "nav.privacy": "Data no privacy",
        "nav.business": "Mode ya business",
        "locales.en": "English",
        "locales.bem": "IciBemba",
        "locales.nya": "IciNyanja",
        "locales.fr": "Français",
        "locales.zh": "中文",
        "common.loading": "Ilekete…",
        "common.backToAccount": "Bweleleni ku account",
        "common.required": "Cafwaikwa",
    },
    "marketing": {
        "notFound.meta.title": "Peji tacasangwa",
        "notFound.code": "404",
        "notFound.heading": "Tatwasanga peji iyi",
        "notFound.body": "Peji mufwaya yaluta nangu tayakwete.",
        "notFound.home": "Piteni ku homepage",
        "notFound.search": "Fweni mu marketplace",
        "notFound.help": "Piteni ku Help Centre",
        "error.meta.title": "Icintu caciluka",
        "error.code": "500",
        "error.heading": "Icintu caciluka",
        "error.body": "Twapoka icilubo. Wesheni limbi — ilyo cikonka, twishibikeni.",
        "error.retry": "Wesheni limbi",
        "error.home": "Piteni ku homepage",
        "error.help": "Piteni ku Help Centre",
    },
}

# ---------------------------------------------------------------------------
# Nyanja (nya) — tone from notifications.json (yanu, Lembani, yatsimikizidwa, …)
# ---------------------------------------------------------------------------
NYA: dict[str, dict[str, str]] = {
    "common": {
        "app.name": "Vergeo5",
        "common.loading": "Ikuyenda…",
        "common.retry": "Yesaninso",
        "nav.home": "Kwathu",
        "nav.skipToContent": "Pitani ku content",
        "theme.label": "Maonekedwe",
        "theme.light": "Kuwala",
        "theme.dark": "Mdima",
        "theme.system": "System ya device",
        "greeting": "Moni, {name}!",
        "offline.code": "Offline",
        "offline.heading": "Mulibe pa network",
        "offline.body": "Palibe connection pano. Mapeji omwe mwaonako kale amagwirabe ntchito — connectaninso kuti muone zonse.",
        "offline.retry": "Yesaninso",
        "offline.home": "Bwererani kwathu",
        "install.title": "Ikani Vergeo5",
        "install.body": "Onjezani Vergeo5 pa home screen kuti mufike mwachangu ndi app ya full-screen.",
        "install.action": "Ika app",
        "install.dismiss": "Osati pano",
        "install.updateBody": "Version yatsopano ya Vergeo5 yalipo.",
        "install.updateAction": "Reload kuti mu-update",
    },
    "catalog": {
        "home.meta.title": "Pezani Zambia",
        "home.meta.description": "Gulani zinthu, bookani services, ndi pezani events mu Zambia pa Vergeo5.",
        "home.nav.ariaLabel": "Navigation ya shop",
        "home.nav.bottomAriaLabel": "Navigation yayikulu ya shop",
        "home.nav.home": "Kwathu",
        "home.nav.browse": "Yang'anani",
        "home.nav.ask": "Funsa",
        "home.nav.orders": "Ma-order",
        "home.nav.account": "Akaunti",
        "home.nav.cart": "Ngolo ya zinthu",
        "home.nav.searchPlaceholder": "Sakani zinthu, services, events…",
        "home.nav.searchSubmit": "Sakani",
        "home.nav.allCategories": "Ma-categories onse",
        "home.nav.categoriesPanelAria": "Ma-categories onse",
        "home.nav.categoriesLoading": "Ikuyenda ma-categories…",
        "home.nav.viewAllCategories": "Onani ma-categories onse",
        "home.nav.services": "Ntchito",
        "home.nav.events": "Zochitika",
        "home.nav.askVergeo": "Funsa Vergeo",
        "home.nav.supplies": "Za business",
        "home.nav.desktopAriaLabel": "Navigation yayikulu",
        "home.hero.eyebrow": "Marketplace ya Zambia",
        "home.hero.fallbackTitle": "Pezani zinthu, services, ndi events mu Zambia",
        "home.hero.fallbackSubtitle": "Fananizani mitengo kuchokera kwa ogulitsa mu Zambia, ndi konzeni delivery ya Lusaka kapena pickup nationwide pamene listing imalola.",
        "home.hero.primaryCta": "Yambani kuyang'ana",
        "home.hero.secondaryCta": "Phunzirani za kugulitsa",
        "home.hero.placeholder.title": "Takulandirani ku Vergeo5",
        "home.hero.placeholder.subtitle": "Storefront yanu ya config idzaonekera apa pamene merchandising slots ziyamba.",
        "home.hero.escrowLine": "Chitetezo cha ogula ndi escrow pamene payment ya online ilipo — ikusungidwa ndi Vergeo5 mpaka kutumiza, kenako yatsimikizidwa.",
        "home.hero.escrowStep1": "Mwalipira",
        "home.hero.escrowStep2": "Ikusungidwa ndi Vergeo5",
        "home.hero.escrowStep3": "Yatsimikizidwa pa kutumiza",
        "home.trust.ariaLabel": "Chifukwa chiyeni mugule pa Vergeo5",
        "home.trust.sellers": "Ma-profiles a ogulitsa ndi status yomwe mungaone",
        "home.trust.fulfillment": "Delivery ya Lusaka kapena pickup nationwide pamene listing imalola",
        "home.trust.returns": "Malangizo a returns ndi refunds pa ma-order oyenera",
        "home.trust.escrow": "Pamene payment ya online ilipo, Vergeo5 imasunga ndalama yanu mpaka kutumiza",
        "home.demo.sampleListing": "Listing ya sample",
        "home.categories.title": "Gulani ndi category",
        "home.categories.viewAll": "Ma-categories onse",
        "home.categories.browseLabel": "Yang'anani {category}",
        "home.rails.newTitle": "Zatsopano pa Vergeo5",
        "home.rails.departmentTitle": "Zatsopano mu {category}",
        "home.rails.viewAll": "Onani zonse",
        "home.rails.servicesTitle": "Ntchito",
        "home.rails.vendorsTitle": "Ogulitsa apamwamba",
        "home.rails.services.provider": "Ndi {provider}",
        "home.rails.services.fromPrice": "Kuyambira",
        "home.rails.services.noReviews": "Provider watsopano",
        "home.rails.services.view": "Onani service",
        "home.rails.vendors.listings": "Zinthu",
        "home.rails.vendors.reviews": "Ma-reviews",
        "home.rails.vendors.rating": "{rating} ({count})",
        "home.rails.vendors.noReviews": "Watsopano",
        "home.rails.vendors.preferred": "Wosankhidwa",
        "home.rails.vendors.verified": "Yatsimikizidwa",
        "home.rails.vendors.location": "Zambia",
        "home.rails.vendors.view": "Pitani ku store",
        "home.sellCta.title": "Kugulitsa pa Vergeo5 ndi kwa invite pano",
        "home.sellCta.body": "Signup ya public sinayatsebe. Ogulitsa oitanidwa atha kupitiriza onboarding; ena atha kuphunzira momwe seller beta imagwirira ntchito.",
        "home.sellCta.cta": "Phunzirani za kugulitsa",
        "browseCategories.title": "Yang'anani ma-categories",
        "browseCategories.subtitle": "Gulani ma-departments a Phase-1 ndi ma-subcategories awo.",
        "browseCategories.emptyTitle": "Palibe ma-categories",
        "browseCategories.emptyBody": "Catalogue ilibe ma-categories a public pano. Bweraninso, kapena sakani.",
        "browseCategories.unavailableTitle": "Ma-categories salipo",
        "browseCategories.unavailableBody": "Sitinathe kutenga category tree pano. Yesaninso, kapena sakani.",
        "plp.title": "Yang'anani {category}",
        "plp.defaultCategory": "Zinthu zonse",
        "plp.breadcrumbAria": "Njira ya peji",
        "plp.results": "{count, plural, one {# listing} other {# ma-listings}}",
        "plp.emptyTitle": "Palibe ma-listings",
        "plp.emptyBody": "Yesani kuchotsa ma-filters kapena yang'anani category ina.",
        "plp.unavailableTitle": "Ma-listings salipo",
        "plp.unavailableBody": "Sitinathe kutenga zinthu za category iyi pano. Yesaninso, kapena sakani.",
        "plp.card.vendor": "Agulitsa {vendor}",
        "plp.card.noReviews": "Palibe ma-reviews",
        "plp.card.reviewCount": "({count})",
        "plp.card.quickAdd": "Onjezani mwachangu",
        "plp.card.wishlist": "Sungani ku wishlist",
        "plp.card.outOfStock": "Palibe mu stock",
        "plp.card.distance": "{distance} kutali",
        "plp.loadMore": "Tengani zina",
        "plp.loading": "Ikuyenda…",
        "pdp.meta.notFoundTitle": "Chinthu sichipezeka",
        "pdp.meta.descriptionFallback": "Gulani {name} pa Vergeo5",
        "pdp.tabs.ariaLabel": "Zinthu za product",
        "pdp.tabs.overview": "Chidule",
        "pdp.tabs.specs": "Za specs",
        "pdp.tabs.reviews": "Ma-reviews",
        "pdp.overview.heading": "Kufotokoza",
        "pdp.related.heading": "Zina mu category iyi",
        "pdp.related.fromPrice": "Kuyambira {price}",
        "pdp.gallery.empty": "Palibe zithunzi",
        "pdp.gallery.indicator": "Chithunzi {current} cha {total}",
        "pdp.gallery.previous": "Chithunzi chapitacho",
        "pdp.gallery.next": "Chithunzi chotsatira",
        "pdp.specs.heading": "Za specs",
        "pdp.specs.empty": "Palibe specifications",
        "pdp.buyBox.priceLabel": "Mtengo",
        "pdp.buyBox.quantityLabel": "Chiwerengero",
        "pdp.buyBox.decrease": "Chepetsani chiwerengero",
        "pdp.buyBox.increase": "Onjezani chiwerengero",
        "pdp.buyBox.decreaseSymbol": "-",
        "pdp.buyBox.increaseSymbol": "+",
        "pdp.buyBox.addToCart": "Onjezani ku cart",
        "pdp.buyBox.addingToCart": "Ikuonjezera…",
        "pdp.buyBox.addToCartError": "Sitinathe kuonjezera ku cart. Onani connection ndi yesaninso.",
        "pdp.buyBox.inStock": "Ili mu stock",
        "pdp.buyBox.outOfStock": "Palibe mu stock",
        "pdp.buyBox.lowStock": "Zatsala {count} zokha",
        "pdp.buyBox.alwaysAvailable": "Ikupezeka",
        "pdp.buyBox.singleVendor": "Agulitsa vendor uyu yekha",
        "pdp.buyBox.moq": "Order yocheperako: {count}",
        "pdp.vendor.heading": "Wogulitsa",
        "pdp.vendor.preferredBadge": "Wogulitsa preferred",
        "pdp.vendor.noReviews": "Palibe ma-reviews",
        "pdp.vendor.rating": "{rating} ({count, plural, one {# review} other {# ma-reviews}})",
        "pdp.vendor.viewStore": "Onani store",
        "pdp.trust.preferredSeller": "Wogulitsa preferred — {name}",
        "pdp.trust.seller": "Agulitsa {name}",
        "pdp.trust.delivery": "Delivery ilipo kwa wogulitsa uyu",
        "pdp.trust.pickup": "Pickup ilipo kwa wogulitsa uyu",
        "pdp.trust.returns": "Returns ndi refunds",
        "pdp.trust.escrow": "Pamene payment ya online ilipo, Vergeo5 imasunga ndalama yanu mpaka kutumiza. COD ingaperekedwe pa ma-order oyenera.",
        "pdp.condition.new": "Yatsopano",
        "pdp.condition.refurbished": "Yokonzedwanso",
        "returnableBadge.label": "Itha kubwezeredwa mkati mwa masiku {days}",
    },
    "search": {
        "title": "Sakani",
        "placeholder": "Sakani pa Vergeo5",
        "submit": "Sakani",
        "recent.title": "Zomwe mwasaka posachedwa",
        "recent.clear": "Chotsani zonse",
        "recent.remove": "Chotsani {term}",
        "tabs.ariaLabel": "Filter results ndi type",
        "tabs.all": "Zonse",
        "tabs.products": "Zinthu",
        "tabs.services": "Ntchito",
        "tabs.events": "Zochitika",
        "tabs.supplies": "Za business",
        "tabs.vendors": "Ogulitsa",
        "tabs.count": "{label} ({count})",
        "noResults.title": "Palibe results za \"{query}\"",
        "noResults.suggestionsTitle": "Yesani kusaka",
        "noResults.categoriesTitle": "Yang'anani ma-categories",
        "unavailable.title": "Search silipo",
        "unavailable.body": "Sitinathe kutenga search results pano. Yesaninso, kapena yang'anani ma-categories.",
        "unavailable.retry": "Yesaninso",
        "invalid.title": "Search iyi ndi yayitali kwambiri",
        "invalid.body": "Fupikitsani query ndi yesaninso. Ma-filters ndi sorting mu URL sizinasintha.",
        "suggestionTerms.phones": "mafoni",
        "suggestionTerms.chitenge": "chitenje",
        "suggestionTerms.kitchenware": "za khitchini",
        "suggestionTerms.lusakaVendors": "ogulitsa a Lusaka",
        "suggestions.term": "Yesani kusaka {term}",
        "categories.electronics": "Za elektrik",
        "categories.fashion": "Za kavalidwe",
        "categories.home": "Kwathu ndi living",
        "categories.groceries": "Groceries ndi staples",
        "askVergeo.title": "Funsa Vergeo",
        "askVergeo.teaser": "Simukudziwa chomwe mufuna? Funsa Vergeo kuti akuthandizeni kupeza chomwe mufuna.",
        "askVergeo.slotLabel": "Slot ya Ask Vergeo assistant",
        "results.count": "{count, plural, one {# result} other {# ma-results}}",
        "results.degraded": "Tikuwonetsa keyword matches (semantic search silipo)",
        "input.ariaLabel": "Sakani",
        "input.suggestionsLabel": "Ma-suggestions a search",
        "input.noSuggestions": "Palibe ma-suggestions",
        "pagination.loadMore": "Tengani zina",
        "pagination.loading": "Ikutenga zina…",
        "result.priceFrom": "Kuyambira {price}",
        "result.category": "Mu {category}",
    },
    "checkout": {
        "cart.title": "Cart yanu",
        "cart.emptyTitle": "Cart yanu ndi yopanda kanthu",
        "cart.emptyBody": "Yang'anani zinthu ndi onjezani items kuti muyambe.",
        "cart.browseCta": "Pitirizani kugula",
        "cart.itemCount": "{count, plural, one {# item} other {# ma-items}}",
        "cart.subtotal": "Subtotal yokha",
        "cart.total": "Zonse",
        "cart.vendorGroup": "Agulitsa vendor",
        "cart.vendorSubtotal": "Subtotal ya vendor: {amount}",
        "cart.lineTotal": "Total ya line: {amount}",
        "cart.unitPrice": "{amount} chimodzi chimodzi",
        "cart.remove": "Chotsani",
        "cart.removeLabel": "Chotsani {title} kuchokera ku cart",
        "cart.qtyDecrease": "Chepetsani chiwerengero",
        "cart.qtyIncrease": "Onjezani chiwerengero",
        "cart.qtyDecreaseSymbol": "-",
        "cart.qtyIncreaseSymbol": "+",
        "cart.qtyValue": "Chiwerengero: {count}",
        "cart.updating": "Ikusintha…",
        "cart.updateError": "Sitinathe kusintha chiwerengero. Tabwerera ku amount yomwe inasungidwa.",
        "cart.addToCart": "Onjezani ku cart",
        "cart.adding": "Ikuonjezera…",
        "cart.added": "Yaonjezedwa ku cart",
        "cart.addError": "Sitinathe kuonjezera ku cart. Yesaninso.",
        "cart.viewCart": "Onani cart",
        "cart.checkoutCta": "Pitani ku checkout",
        "cart.miniCartTitle": "Summary ya cart",
        "cart.miniCartClose": "Tsekani cart",
        "cart.openCart": "Tsekulani cart",
        "cart.deliveryEligible": "Subtotal ya vendor ikuyenera free Lusaka delivery — zone itsimikizidwa pa checkout",
        "cart.deliveryHint": "Onjezani {amount} kuchokera kwa vendor uyu kuti mukwaniritse free Lusaka delivery",
        "cart.deliveryThreshold": "Free Lusaka delivery kuyambira {threshold} pa vendor",
        "cart.deliveryScopeNote": "Imagwira ntchito mkati mwa ma-zones a delivery a Lusaka. Kunja kwa Lusaka, pickup ilipo. Ma-fees a zone amagwirabe ntchito pansi pa threshold.",
        "cart.freeDeliveryProgress": "{amount} ya {threshold} ku free Lusaka delivery",
        "cart.freeDeliveryUnlocked": "Subtotal ya vendor iyi ikuyenera free Lusaka delivery",
        "cart.noticesTitle": "Zina zasintha",
        "cart.noticePriceChanged": "Mtengo wasintha kuchokera {oldPrice} ku {newPrice}",
        "cart.noticeOutOfStock": "Chinthu ichi sichilipo mu stock",
        "cart.noticeQtyReduced": "Zatsala {available} zokha — chiwerengero chasintha kuchokera {requested}",
        "cart.outOfStockLine": "Palibe mu stock",
        "checkout.pageTitle": "Kugula",
        "checkout.stepAnnouncement": "Step {current} ya {total}",
        "checkout.doneIndicator": "✓",
        "checkout.steps.contact": "Contact yanu",
        "checkout.steps.fulfilment": "Kutumiza",
        "checkout.steps.payment": "Kulipira",
        "checkout.steps.review": "Kuona",
        "checkout.payment.title": "Mungafune kulipira bwanji?",
        "checkout.payment.subtitle": "Payment yanu ikusungidwa bwino mpaka kutumiza.",
        "checkout.payment.momo": "Ndalama za mobile",
        "checkout.payment.card": "Debit kapena credit card",
        "checkout.payment.cod": "Cash ikafika",
        "checkout.payment.railMtn": "MTN MoMo",
        "checkout.payment.railAirtel": "Airtel Money (MoMo)",
        "checkout.payment.payerLabel": "Nambala ya payer",
        "checkout.payment.payerHelp": "Nambala yomwe idzalandira USSD payment prompt.",
        "checkout.payment.payerPlaceholder": "97X XXX XXX",
        "checkout.payment.countryCode": "Code ya dziko",
        "checkout.payment.nationalNumber": "Nambala ya mobile",
        "checkout.payment.cardExplainer": "Mukatha kuyika order, mukamaliza card payment pa Lenco secure hosted page. Vergeo5 siimaona zinthu za card yanu.",
        "checkout.payment.codIneligible": "Cash on delivery ili yokha pa ma-order mpaka {cap}.",
        "checkout.payment.continue": "Pitirizani ku review",
        "checkout.payment.loading": "Dikirani…",
        "checkout.payment.required": "Lembani nambala ya payer",
        "checkout.payment.invalidPayer": "Lembani nambala ya Zambia yovomerezeka",
        "checkout.payment.railRequired": "Sankhani mobile money network",
        "checkout.payment.codRejected": "Cash on delivery silipo pa total iyi ya order",
        "checkout.payment.railRejected": "Mobile money network iyi sivomerezedwa",
        "checkout.payment.error": "Sitinathe kusunga payment method. Yesaninso.",
        "checkout.payment.paymentsDisabled": "Payment ya online silipo pano. Gwiritsani ntchito Cash on Delivery pamene ilipo, kapena yesaninso posachedwa.",
        "checkout.review.title": "Onani order yanu",
        "checkout.review.subtitle": "Onani kuti zonse zili bwino musanalipire.",
        "checkout.review.lineItems": "Zinthu",
        "checkout.review.qty": "×{qty}",
        "checkout.review.subtotal": "Subtotal yokha",
        "checkout.review.deliveryFees": "Ma-fees a delivery",
        "checkout.review.total": "Zonse",
        "checkout.review.paymentMethod": "Njira yolipira",
        "checkout.review.methodMomo": "Ndalama za mobile ({rail})",
        "checkout.review.methodCard": "Card (secure hosted page)",
        "checkout.review.methodCod": "Cash ikafika",
        "checkout.review.railMtn": "MTN",
        "checkout.review.railAirtel": "Airtel",
        "checkout.review.payerNumber": "Wolipira: {number}",
        "checkout.review.escrowTitle": "Momwe payment yanu imatetezedwa",
        "checkout.review.escrowStep1": "Mwalipira",
        "checkout.review.escrowStep2": "Ikusungidwa ndi Vergeo5",
        "checkout.review.escrowStep3": "Yatsimikizidwa pa kutumiza",
        "checkout.review.consentLabel": "Ndikuvomera Terms & Conditions ndi Privacy Policy",
        "checkout.review.consentRequired": "Vomerani Terms & Conditions kuti mupitirize",
        "checkout.review.placeOrder": "Ikani order",
        "checkout.review.loading": "Dikirani…",
        "checkout.pending.pageTitle": "Tsimikizani payment",
        "checkout.pending.loading": "Ikuona payment status…",
        "checkout.pending.error": "Sitinathe kutenga payment status. Yesaninso.",
        "checkout.pending.pollAria": "Tikudikira approval ya mobile money",
        "checkout.pending.successRedirect": "Tikukupitani ku order yanu…",
        "checkout.pending.confirmingTitle": "Tikutsimikiza payment yanu",
        "checkout.pending.confirmingBody": "Talandira signal ya payment ndipo tikutsimikiza order yanu. Izi si final paid confirmation — onani order status pa escrow updates.",
        "checkout.pending.codTitle": "Order yaiyikidwa — lipirani pa delivery",
        "checkout.pending.codBody": "Khalani ndi {amount} mu cash pamene order yanu ifika. Courier wathu adzatenga payment pa delivery.",
        "checkout.pending.codCta": "Onani zinthu za order",
        "checkout.pending.cancelledTitle": "Payment yacotsedwa",
        "checkout.pending.cancelledBody": "Mwadana mobile money prompt. Mutha kuyesanso kapena sankhani payment method ina pa checkout.",
        "checkout.pending.cancelledCta": "Bwererani ku checkout",
        "checkout.pending.timeoutTitle": "Payment yatha nthawi",
        "checkout.pending.timeoutBody": "USSD prompt yatha nthawi isanatsimikizidwe. Onani kuti phone yanu ili ndi network, kenako yesaninso — titumiza prompt yatsopano pa order yomweyo.",
        "checkout.pending.retry": "Yesaninso payment",
        "checkout.pending.retrying": "Ikutumiza prompt yatsopano…",
        "checkout.pending.retryError": "Sitinathe kuyesanso payment. Onani connection ndi yesaninso.",
        "checkout.pending.viewOrder": "Onani order",
        "checkout.ussd.title": "Onani phone yanu",
        "checkout.ussd.subtitle": "Tsimikizani prompt ya {amount} pa phone yanu kuti mumalize payment.",
        "checkout.ussd.amountLabel": "Amount yotsimikizira",
        "checkout.ussd.mtnHelp": "Tsekulani MTN MoMo prompt pa phone yanu ndi lembani PIN kuti mutsimikize {amount}.",
        "checkout.ussd.airtelHelp": "Tsekulani Airtel Money prompt pa phone yanu ndi lembani PIN kuti mutsimikize {amount}.",
        "checkout.ussd.genericHelp": "Mobile money prompt yatumizidwa ku phone yanu. Lembani PIN kuti mutsimikize {amount}.",
        "checkout.ussd.waiting": "Tikudikira approval…",
        "checkout.ussd.doNotClose": "Sungani peji iyi ili open pamene mukutsimikiza pa phone.",
        "checkout.card.pageTitle": "Lipirani ndi card",
        "checkout.card.subtitle": "Malizani payment yanu secure pa Lenco. Vergeo5 siimaona zinthu za card yanu.",
        "checkout.card.loading": "Ikukonza secure payment…",
        "checkout.card.openingWidget": "Ikutsekula Lenco secure payment…",
        "checkout.card.verifying": "Ikuona payment yanu…",
        "checkout.card.successTitle": "Order yatsimikizidwa",
        "checkout.card.successBody": "Order yanu yatsimikizidwa ndipo payment ikusungidwa ndi Vergeo5. Mutha kuona zinthu za order pano.",
        "checkout.card.viewOrders": "Onani ma-order anu",
        "checkout.card.failedTitle": "Payment sinamalizidwe",
        "checkout.card.failedBody": "Card payment sinapite. Mutha kuyesanso kuchokera ku checkout.",
        "checkout.card.retryPayment": "Bwererani ku payment",
        "checkout.card.heldTitle": "Payment ikuwunikiridwa",
        "checkout.card.heldBody": "Sitinathe kutsimikiza payment iyi automatic. Team yathu yadziwitsidwa — musalipirenso mpaka titsimikize.",
        "checkout.card.pendingTitle": "Ikupitiriza",
        "checkout.card.pendingBody": "Tikudikira final confirmation kuchokera ku Lenco. Peji iyi idzasintha posachedwa.",
        "checkout.card.error": "China chake chalakwika. Yesaninso.",
        "checkout.card.widgetUnavailable": "Card payments sizilipo pano. Yesani mobile money kapena yesaninso pambuyo.",
        "checkout.card.widgetLabel": "Order ya Vergeo5",
        "checkout.card.secureNote": "Yotetezedwa ndi Lenco — PCI compliant hosted checkout",
        "checkout.emptyCart": "Cart yanu ndi yopanda kanthu.",
        "checkout.error": "China chake chalakwika. Yesaninso.",
        "checkout.loading": "Ikuyamba checkout…",
        "checkout.stockUnavailable": "Chinthu sichilipo. Onani cart yanu.",
        "checkout.reservationExpired": "Reservation yanu yatha — zinthu zabwerera ku cart yanu.",
    },
    "orders": {
        "title": "Ma-order anu",
        "empty.title": "Palibe ma-order",
        "empty.body": "Mukagula kuchokera kwa ogulitsa a Vergeo5, ma-order ndi tracking zidzaonekera apa.",
        "empty.cta": "Yambani kugula",
        "list.checkoutGroup": "Kugula {date}",
        "list.vendorOrder": "Kuchokera kwa {vendor}",
        "list.itemCount": "{count, plural, one {# item} other {# ma-items}}",
        "list.total": "Zonse {amount}",
        "list.viewOrder": "Onani order",
        "list.status": "Status ndi: {status}",
        "list.paymentCod": "Lipirani pa delivery",
        "list.paymentPrepaid": "Yalipidwa kale",
        "detail.title": "Zinthu za order",
        "detail.back": "Bwererani ku ma-order",
        "detail.orderId": "Order nambala {id}",
        "detail.vendor": "Agulitsa {vendor}",
        "detail.total": "Total ya order",
        "status.placed": "Yaiyikidwa",
        "status.confirmed": "Yatsimikizidwa",
        "status.processing": "Ikukonzedwa",
        "status.ready": "Yakonzeka ku pickup",
        "status.shipped": "Yatumizidwa",
        "status.delivered": "Yafika",
        "status.completed": "Yamalizidwa",
        "status.cancelled": "Yacotsedwa",
        "status.refunded": "Refund ikuyenda",
        "timeline.title": "Progress ya order",
        "timeline.placed": "Order yaiyikidwa",
        "timeline.paymentHeld": "Mwalipira — ikusungidwa ndi Vergeo5",
        "timeline.paymentCod": "Lipirani vendor pa delivery",
        "timeline.confirmed": "Vendor yatsimikiza order yanu",
        "timeline.processing": "Vendor ikukonza order yanu",
        "timeline.ready": "Yakonzeka ku pickup",
        "timeline.shipped": "Ikubwera kwa inu",
        "timeline.delivered": "Yafika",
        "timeline.completed": "Payment yatsimikizidwa kwa vendor",
        "timeline.cancelled": "Order yacotsedwa",
        "timeline.refunded": "Refund ku mobile money yanu",
        "escrow.held": "Payment yanu ikusungidwa ndi Vergeo5 mpaka mulandire order yanu.",
        "escrow.released": "Ndalama zatsimikizidwa kwa vendor pambuyo pa fulfilment.",
        "escrow.refunded": "Refund ikubwerera ku mobile money wallet yanu.",
        "escrow.cod": "Lipirani vendor mu cash kapena mobile money mukalandira order.",
        "errors.loadFailed": "Sitinathe kutenga ma-order anu. Yesaninso.",
        "errors.notFound": "Order sichipezeka",
    },
    "account": {
        "title": "Account yanga",
        "nav.profile": "Profile yanu",
        "nav.addresses": "Ma-addresses",
        "nav.preferences": "Ma-notifications",
        "nav.privacy": "Data ndi privacy",
        "nav.business": "Mode ya business",
        "locales.en": "English",
        "locales.bem": "IciBemba",
        "locales.nya": "IciNyanja",
        "locales.fr": "Français",
        "locales.zh": "中文",
        "common.loading": "Ikuyenda…",
        "common.backToAccount": "Bwererani ku account",
        "common.required": "Zofunika",
    },
    "marketing": {
        "notFound.meta.title": "Peji sichipezeka",
        "notFound.code": "404",
        "notFound.heading": "Sitinapeze peji iyo",
        "notFound.body": "Peji yomwe mukufuna yatha kusamuka kapena kulibe.",
        "notFound.home": "Pitani ku homepage",
        "notFound.search": "Sakani mu marketplace",
        "notFound.help": "Pitani ku Help Centre",
        "error.meta.title": "China chake chalakwika",
        "error.code": "500",
        "error.heading": "China chake chalakwika",
        "error.body": "Tinakumana ndi vuto. Yesaninso — ngati zikupitirira, tidziwitseni.",
        "error.retry": "Yesaninso",
        "error.home": "Pitani ku homepage",
        "error.help": "Pitani ku Help Centre",
    },
}


def write_overlays(locale: str, translations: dict[str, dict[str, str]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for ns, prefixes in PREFIXES.items():
        en = json.loads((MSG / "en" / f"{ns}.json").read_text(encoding="utf-8"))
        en_flat = flatten(en)
        critical_keys = sorted(k for k in en_flat if matches(k, prefixes))
        loc_map = translations[ns]
        missing = [k for k in critical_keys if k not in loc_map]
        if missing:
            raise SystemExit(f"{locale}/{ns}: missing {len(missing)} keys: {missing[:10]}")
        # Only write critical keys (overlay), preserving nested shape
        overlay_flat = {k: loc_map[k] for k in critical_keys}
        nested = unflatten(overlay_flat)
        out_path = MSG / locale / f"{ns}.json"
        out_path.write_text(
            json.dumps(nested, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        counts[f"{locale}/{ns}.json"] = len(overlay_flat)
        print(f"Wrote {out_path.relative_to(ROOT)} ({len(overlay_flat)} keys)")
    return counts


def main() -> None:
    counts = {}
    counts.update(write_overlays("bem", BEM))
    counts.update(write_overlays("nya", NYA))
    print("\nKey counts:")
    for path, n in counts.items():
        print(f"  {path}: {n}")
    print(f"  TOTAL: {sum(counts.values())}")


if __name__ == "__main__":
    main()
